# Generated by Django 4.1.3 on 2022-12-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.CharField(max_length=50, verbose_name='log_time')),
                ('time', models.CharField(max_length=50, verbose_name='timeStamp')),
                ('user', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='user')),
                ('nice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='nice')),
                ('system', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='system')),
                ('iowait', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='iowait')),
                ('steal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='steal')),
                ('host_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.host')),
            ],
        ),
    ]
