# Generated by Django 4.1.6 on 2023-02-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcaPeaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='peak')),
                ('host_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.host')),
            ],
        ),
    ]
